language: rust
sudo: required
dist: trusty
rust: stable
services:
  - docker

# Install an updated version of docker
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine

install:
  # needed for linting JS below
  - npm install jshint
  # this is a dependency of playpen currently
  - sudo pip install pygments

script:
  - find static/ -iname "*.js" | xargs jshint
  - cargo build
  - sh docker/build.sh
  - cargo test

notifications:
  email:
    on_success: never
